# docker-compose.yml
version: "3"
services:
  app:
    build: .
    container_name: MovieApi
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@host.docker.internal:35432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
