# docker-compose.yml
version: "3"
services:
  app:
    build: .
    container_name: MovieApi
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    env_file:
      - .env
